version: '3.7'
name: 'amazon-books-analyzer'

services:
  rabbitmq:
    build:
      context: rabbitmq/
      dockerfile: Dockerfile
      args:
        RABBITMQ_VERSION: $RABBITMQ_VERSION
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-}
    volumes:
      - type: bind
        source: ./rabbitmq/config/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
        read_only: true
      - type: bind
        source: ./rabbitmq/config/definitions.json
        target: /etc/rabbitmq/definitions.json
        read_only: true
      - type: volume
        source: rabbitmq
        target: /var/lib/rabbitmq
    networks:
      - network-bridge
    hostname: rabbitmq
    ports:
    - 15672:15672

  # rabbitmq-test:
  #   build:
  #     context: rabbitmq-test/
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - ID=0
    volumes:
      - ../data:/data
    networks:
      - network-bridge
    hostname: client
    depends_on:
      - cleaner

  # client1:
  #   build:
  #     context: .
  #     dockerfile: ./client/Dockerfile
  #   environment:
  #     - ID=1
  #   volumes:
  #     - ../data:/data
  #   networks:
  #     - network-bridge
  #   hostname: client1
  #   depends_on:
  #     - cleaner

  cleaner:
      build:
        context: .
        dockerfile: ./data_cleaner/Dockerfile
      networks:
        - network-bridge
      depends_on:
        - rabbitmq

  filter1:
    build:
      context: .
      dockerfile: ./filter/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
    environment:
      - LOG_QUEUE=log.filter1
  
  # filter2:
  #   build:
  #     context: .
  #     dockerfile: ./filter/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  # filter3:
  #   build:
  #     context: .
  #     dockerfile: ./filter/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  joiner1:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=1
      - LOG_QUEUE_BOOKS=log.joiner1_books
      - LOG_QUEUE_REVIEWS=log.joiner1_reviews
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
  
  joiner2:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=2
      - LOG_QUEUE_BOOKS=log.joiner2_books
      - LOG_QUEUE_REVIEWS=log.joiner2_reviews
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

  joiner3:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=3
      - LOG_QUEUE_BOOKS=log.joiner3_books
      - LOG_QUEUE_REVIEWS=log.joiner3_reviews
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

  joiner4:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=4
      - LOG_QUEUE_BOOKS=log.joiner4_books
      - LOG_QUEUE_REVIEWS=log.joiner4_reviews
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

  # joiner5:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=5
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # joiner6:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=6
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  # joiner7:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=7
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  # joiner8:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=8
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge 

  # joiner9:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=9
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge 
  
  # joiner10:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=10
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge 

  counter:
    build:
      context: .
      dockerfile: ./counter/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
    environment:
      - LOG_QUEUE=log.counter
    
  sentiment-analyzer1:
    build:
      context: .
      dockerfile: ./sentiment_analyzer/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
    environment:
      - LOG_QUEUE=log.sentiment_analyzer1
  
  sentiment-analyzer2:
    build: 
      context: .
      dockerfile: ./sentiment_analyzer/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
    environment:
      - LOG_QUEUE=log.sentiment_analyzer2

  sentiment-analyzer3:
    build: 
      context: .
      dockerfile: ./sentiment_analyzer/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
    environment:
      - LOG_QUEUE=log.sentiment_analyzer3
  
  # sentiment-analyzer4:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment_analyzer/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer5:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment_analyzer/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  # sentiment-analyzer6:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment_analyzer/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  # sentiment-analyzer7:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment_analyzer/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer8:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment_analyzer/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer9:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment_analyzer/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer10:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment_analyzer/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer11:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment_analyzer/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer12:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment_analyzer/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

networks:
  network-bridge:

volumes:
  rabbitmq: