version: '3.7'
name: 'amazon-books-analyzer'

services:
  rabbitmq1:
    build:
      context: rabbitmq/
      dockerfile: Dockerfile
      args:
        RABBITMQ_VERSION: $RABBITMQ_VERSION
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-}
    volumes:
      - ./rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/config/definitions.json:/etc/rabbitmq/definitions.json
      - type: volume
        source: rabbitmq
        target: /var/lib/rabbitmq
    networks:
      - network-bridge
    hostname: rabbitmq
    ports:
    - 15672:15672

  # rabbitmq-test:
  #   build:
  #     context: rabbitmq-test/
  #     dockerfile: Dockerfile
  #   networks:
  #     - network-bridge

  client1:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - ID=1
    volumes:
      - ../data:/data
    networks:
      - network-bridge
    hostname: client

  client2:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - ID=2
    volumes:
      - ../data:/data
    networks:
      - network-bridge
    hostname: client1

  cleaner1:
    build:
      context: .
      dockerfile: ./data_cleaner/Dockerfile
    networks:
      - network-bridge

  filter1:
    build:
      context: .
      dockerfile: ./filter/Dockerfile
    networks:
      - network-bridge
  
  # filter2:
  #   build:
  #     context: .
  #     dockerfile: ./filter/Dockerfile
  #   networks:
  #     - network-bridge

  # filter3:
  #   build:
  #     context: .
  #     dockerfile: ./filter/Dockerfile
  #   networks:
  #     - network-bridge

  joiner1:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=1
    networks:
      - network-bridge
  
  joiner2:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=2
    networks:
      - network-bridge

  joiner3:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=3
    networks:
      - network-bridge

  joiner4:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=4
    networks:
      - network-bridge

  # joiner5:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=5
  #   networks:
  #     - network-bridge
  
  # joiner6:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=6
  #   networks:
  #     - network-bridge

  # joiner7:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=7
  #   networks:
  #     - network-bridge

  # joiner8:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=8
  #   networks:
  #     - network-bridge 

  # joiner9:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=9
  #   networks:
  #     - network-bridge 
  
  # joiner10:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=10
  #   networks:
  #     - network-bridge 

  counter1:
    build:
      context: .
      dockerfile: ./counter/Dockerfile
    networks:
      - network-bridge
    
  sentiment-analyzer1:
    build:
      context: .
      dockerfile: ./sentiment-analyzer/Dockerfile
    networks:
      - network-bridge
  
  sentiment-analyzer2:
    build: 
      context: .
      dockerfile: ./sentiment-analyzer/Dockerfile
    networks:
      - network-bridge

  sentiment-analyzer3:
    build: 
      context: .
      dockerfile: ./sentiment-analyzer/Dockerfile
    networks:
      - network-bridge
  
  # sentiment-analyzer4:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyzer/Dockerfile
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer5:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyzer/Dockerfile
  #   networks:
  #     - network-bridge

  # sentiment-analyzer6:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyzer/Dockerfile
  #   networks:
  #     - network-bridge

  # sentiment-analyzer7:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyzer/Dockerfile
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer8:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyzer/Dockerfile
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer9:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyzer/Dockerfile
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer10:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyzer/Dockerfile
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer11:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyzer/Dockerfile
  #   networks:
  #     - network-bridge
  
  # sentiment-analyzer12:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyzer/Dockerfile
  #   networks:
  #     - network-bridge
  medic:
    build:
      context: .
      dockerfile: ./medic/Dockerfile
    environment:
      - ID=0
    networks:
      - network-bridge
    hostname: medic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  network-bridge:

volumes:
  rabbitmq: