version: '3.7'
name: 'amazon-books-analyzer'

services:
  rabbitmq:
    build:
      context: rabbitmq/
      dockerfile: Dockerfile
      args:
        RABBITMQ_VERSION: $RABBITMQ_VERSION
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-}
    volumes:
      - type: bind
        source: ./rabbitmq/config/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
        read_only: true
      - type: bind
        source: ./rabbitmq/config/definitions.json
        target: /etc/rabbitmq/definitions.json
        read_only: true
      - type: volume
        source: rabbitmq
        target: /var/lib/rabbitmq
    networks:
      - network-bridge
    hostname: rabbitmq
    ports:
    - 15672:15672

  # rabbitmq-test:
  #   build:
  #     context: rabbitmq-test/
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
 #     - ../data/data.zip:/data.zip
      - ../data:/data
    networks:
      - network-bridge
    depends_on:
      - cleaner

  cleaner:
    build:
      context: .
      dockerfile: ./data_cleaner/Dockerfile
    networks:
      - network-bridge
    depends_on:
      - rabbitmq

  filter1:
    build:
      context: .
      dockerfile: ./filter/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
  
  # filter2:
  #   build:
  #     context: .
  #     dockerfile: ./filter/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  # filter3:
  #   build:
  #     context: .
  #     dockerfile: ./filter/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  joiner1:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=1
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
  
  joiner2:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=2
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

  joiner3:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=3
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

  joiner4:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=4
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

  joiner5:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=5
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
  
  # joiner6:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=6
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  # joiner7:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=7
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  # joiner8:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=8
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge 

  # joiner9:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=9
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge 
  
  # joiner10:
  #   build:
  #     context: .
  #     dockerfile: ./joiner/Dockerfile
  #   environment:
  #     - ID=10
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge 

  counter:
    build:
      context: .
      dockerfile: ./counter/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
    
  sentiment-analyser1:
    build:
      context: .
      dockerfile: ./sentiment-analyser/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
  
  sentiment-analyser2:
    build: 
      context: .
      dockerfile: ./sentiment-analyser/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

  sentiment-analyser3:
    build: 
      context: .
      dockerfile: ./sentiment-analyser/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
  
  sentiment-analyser4:
    build: 
      context: .
      dockerfile: ./sentiment-analyser/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
  
  sentiment-analyser5:
    build: 
      context: .
      dockerfile: ./sentiment-analyser/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

  # sentiment-analyser6:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyser/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

  # sentiment-analyser7:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyser/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # sentiment-analyser8:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyser/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # sentiment-analyser9:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyser/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # sentiment-analyser10:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyser/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # sentiment-analyser11:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyser/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge
  
  # sentiment-analyser12:
  #   build: 
  #     context: .
  #     dockerfile: ./sentiment-analyser/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - network-bridge

networks:
  network-bridge:

volumes:
  rabbitmq: