version: '3.7'
name: 'amazon-books-analyzer'

services:
  rabbitmq:
    build:
      context: rabbitmq/
      dockerfile: Dockerfile
      args:
        RABBITMQ_VERSION: $RABBITMQ_VERSION
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-}
    volumes:
      - type: bind
        source: ./rabbitmq/config/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
        read_only: true
      - type: bind
        source: ./rabbitmq/config/definitions.json
        target: /etc/rabbitmq/definitions.json
        read_only: true
      - type: volume
        source: rabbitmq
        target: /var/lib/rabbitmq
    networks:
      - network-bridge
    hostname: rabbitmq
    ports:
    - 15672:15672

  rabbitmq-test:
    build:
      context: rabbitmq-test/
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ../data:/data
    networks:
      - network-bridge
    depends_on:
      - cleaner

  cleaner:
    build:
      context: .
      dockerfile: ./data_cleaner/Dockerfile
    networks:
      - network-bridge
    depends_on:
      - rabbitmq

  filter:
    build:
      context: .
      dockerfile: ./filter/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

  joiner:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

  counter:
    build:
      context: .
      dockerfile: ./counter/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge
    
  sentiment-analyser:
    build:
      context: .
      dockerfile: ./sentiment-analyser/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network-bridge

networks:
  network-bridge:

volumes:
  rabbitmq: