name: 'amazon-books-analyzer'

services:
  rabbitmq1:
    build:
      context: rabbitmq/
      dockerfile: Dockerfile
      args:
        RABBITMQ_VERSION: $RABBITMQ_VERSION
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-}
    volumes:
      - ./rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/config/definitions.json:/etc/rabbitmq/definitions.json
      - type: volume
        source: rabbitmq
        target: /var/lib/rabbitmq
    networks:
      - network-bridge
    hostname: rabbitmq
    ports:
    - 15672:15672

  # rabbitmq-test:
  #   build:
  #     context: rabbitmq-test/
  #     dockerfile: Dockerfile
  #   networks:
  #     - network-bridge

  client1:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - ID=1
    volumes:
      - ../data:/data
    networks:
      - network-bridge
    hostname: client1

  # client2:
  #   build:
  #     context: .
  #     dockerfile: ./client/Dockerfile
  #   environment:
  #     - ID=2
  #   volumes:
  #     - ../data:/data
  #   networks:
  #     - network-bridge
  #   hostname: client2

  cleaner1:
    build:
      context: .
      dockerfile: ./data_cleaner/Dockerfile
    networks:
      - network-bridge
    depends_on:
      - rabbitmq1
      - medic

  filter1:
    build:
      context: .
      dockerfile: ./filter/Dockerfile
    environment:
      - ID=1
      - LOG_PATH=/logs/filter1.log
    networks:
      - network-bridge
    volumes:
      - ../logs:/logs
    depends_on:
      - rabbitmq1
      - medic
  
  # filter2:
  #   build:
  #     context: .
  #     dockerfile: ./filter/Dockerfile
  #   networks:
  #     - network-bridge
  #   volumes:
  #     - ../logs:/logs
  #   environment:
  #     - LOG_PATH=/logs/filter2.log
  # depends_on:
  #     - rabbitmq1
  # - medic

  # filter3:
  #   build:
  #     context: .
  #     dockerfile: ./filter/Dockerfile
  #   networks:
  #     - network-bridge
  #   volumes:
  #     - ../logs:/logs
  #   environment:
  #     - LOG_PATH=/logs/filter3.log
  # depends_on:
  #     - rabbitmq1
  # - medic

  joiner1:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=1
      - LOG_PATH_BOOKS=/logs/joiner1_books.log
      - LOG_PATH_REVIEWS=/logs/joiner1_reviews.log
    networks:
      - network-bridge
    volumes:
      - ../logs:/logs
    depends_on:
      - rabbitmq1
      - medic
  
  joiner2:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=2
      - LOG_PATH_BOOKS=/logs/joiner2_books.log
      - LOG_PATH_REVIEWS=/logs/joiner2_reviews.log
    volumes:
      - ../logs:/logs
    networks:
      - network-bridge
    depends_on:
      - rabbitmq1
      - medic

  joiner3:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=3
      - LOG_PATH_BOOKS=/logs/joiner3_books.log
      - LOG_PATH_REVIEWS=/logs/joiner3_reviews.log
    volumes:
      - ../logs:/logs
    networks:
      - network-bridge
    depends_on:
      - rabbitmq1
      - medic

  joiner4:
    build:
      context: .
      dockerfile: ./joiner/Dockerfile
    environment:
      - ID=4
      - LOG_PATH_BOOKS=/logs/joiner4_books.log
      - LOG_PATH_REVIEWS=/logs/joiner4_reviews.log
    depends_on:
      - rabbitmq1
    networks:
      - network-bridge
    volumes:
      - ../logs:/logs

  counter1:
    build:
      context: .
      dockerfile: ./counter/Dockerfile
    environment:
      - ID=1
      - LOG_PATH=/logs/counter.log
    networks:
      - network-bridge
    volumes:
      - ../logs:/logs
    depends_on:
      - rabbitmq1
      - medic
    
  sentiment-analyzer1:
    build:
      context: .
      dockerfile: ./sentiment_analyzer/Dockerfile
    volumes:
      - ../logs:/logs
    environment:
      - LOG_PATH=/logs/sentiment_analyzer1.log
      - ID=1
    networks:
      - network-bridge
    depends_on:
      - rabbitmq1
      - medic
  
  sentiment-analyzer2:
    build: 
      context: .
      dockerfile: ./sentiment_analyzer/Dockerfile
    volumes:
      - ../logs:/logs
    environment:
      - LOG_PATH=/logs/sentiment_analyzer2.log
      - ID=2
    networks:
      - network-bridge
    depends_on:
      - rabbitmq1
      - medic
  
  sentiment-analyzer3:
    build: 
      context: .
      dockerfile: ./sentiment_analyzer/Dockerfile
    volumes:
      - ../logs:/logs
    environment:
      - LOG_PATH=/logs/sentiment_analyzer3.log
      - ID=3
    networks:
      - network-bridge
    depends_on:
      - rabbitmq1
      - medic

  sentiment-analyzer4:
    build: 
      context: .
      dockerfile: ./sentiment_analyzer/Dockerfile
    volumes:
      - ../logs:/logs
    environment:
      - LOG_PATH=/logs/sentiment_analyzer4.log
      - ID=4
    networks:
      - network-bridge
    depends_on:
      - rabbitmq1
      - medic
  
  sentiment-analyzer5:
    build: 
      context: .
      dockerfile: ./sentiment_analyzer/Dockerfile
    volumes:
      - ../logs:/logs
    environment:
      - LOG_PATH=/logs/sentiment_analyzer5.log
      - ID=5
    networks:
      - network-bridge
    depends_on:
      - rabbitmq1
      - medic

  medic:
    build:
      context: .
      dockerfile: ./medic/Dockerfile
    environment:
      - ID=0
    networks:
      - network-bridge
    hostname: medic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  network-bridge:

volumes:
  rabbitmq: